Repository Arelle/Arelle, pull requests merged in 2022-09, with the labels that each got.

#303 Partly move setup.py config to pyproject.toml
  pyproject.toml
  setup.py
Labels: approved

#318 [Table Linkbase] Fix the case 0120 from the table linkbase conformance suite
  arelle/RenderingEvaluator.py
Labels: approved, enhancement

#316 Fix some python error after the refactor of the table linkbase
  arelle/ModelRenderingObject.py
  arelle/RenderingResolution.py
  arelle/ViewFileRenderedGrid.py
Labels: approved, bug

#313 add type hints Cntlr.py and related files round01
  arelle/Cntlr.py
  arelle/Locale.py
  arelle/ModelManager.py
  arelle/ModelXbrl.py
  arelle/PackageManager.py
  arelle/PluginManager.py
  arelle/WebCache.py
  pyproject.toml
Labels: approved, enhancement

#310 Add type hints for arelle/ValidateXbrl.py and ancillary files
  .gitignore
  arelle/ModelDtsObject.py
  arelle/ModelInstanceObject.py
  arelle/ModelXbrl.py
  arelle/PluginManager.py
  arelle/ValidateFormula.py
  arelle/ValidateUtr.py
  arelle/ValidateXbrl.py
  arelle/ValidateXbrlCalcs.py
  arelle/ValidateXbrlDTS.py
  arelle/ValidateXbrlDimensions.py
  arelle/XbrlConst.py
  arelle/XbrlUtil.py
  arelle/XhtmlValidate.py
  arelle/XmlUtil.py
  arelle/XmlValidateParticles.py
  pyproject.toml
Labels: approved, enhancement

#326 Update the table linkbase conformance suite.
  scripts/conformance_suites/run_xbrl_table_linkbase_conformance_suite.py
  tests/integration_tests/validation/XBRL/test_xbrl_table_linkbase_conformance_suite.py
Labels: enhancement

#325 Add type hints for arelle.UrlUtil
  arelle/UrlUtil.py
  pyproject.toml
Labels: enhancement

#327 Update the table linkbase conformance suite.
  scripts/conformance_suites/run_xbrl_table_linkbase_conformance_suite.py
  tests/integration_tests/validation/XBRL/test_xbrl_table_linkbase_conformance_suite.py
Labels: enhancement

#328 Add type hints arelle.ModelObject.py
  arelle/ModelObject.py
  arelle/ValidateXbrl.py
  arelle/plugin/validate/ESEF/Util.py
  arelle/plugin/validate/ESEF/__init__.py
  pyproject.toml
Labels: approved, enhancement

#321 Auto add to project workflow
  .github/workflows/project.yml
Labels: enhancement

#360 Add initial support for system info reporting
  arelle/CntlrCmdLine.py
  arelle/SystemInfo.py
  pyproject.toml
  tests/unit_tests/arelle/test_system_info.py
Labels: enhancement

#343 Add type hints to arelle.XbrlUtil
  arelle/ModelObject.py
  arelle/XbrlUtil.py
  pyproject.toml
Labels: enhancement

#342 Add type hints to arelle.XbrlConst
  arelle/ModelObject.py
  arelle/ModelValue.py
  arelle/XbrlConst.py
  arelle/XbrlUtil.py
  pyproject.toml
Labels: enhancement

#341 Add type hints to arelle.Locale
  arelle/Locale.py
  arelle/ModelObject.py
  arelle/typing.py
  pyproject.toml
  tests/unit_tests/arelle/test_locale.py
Labels: enhancement

#367 Make distribution artifact names consistent
  .github/workflows/build-mac.yml
  .github/workflows/build-windows.yml
Labels: enhancement

#185 Convert the Formula conformance suite tests to pytest.
  arelle/CntlrCmdLine.py
  arelle/ModelDocument.py
  arelle/ModelManager.py
  arelle/ModelValue.py
  pyproject.toml
  scripts/conformance_suites/run_formula_conformance_suite.py
  scripts/conformance_suites/run_formula_function_registry_conformance_suite.py
  scripts/runFormulaTests-27.bat
  scripts/runFormulaTests.bat
  scripts/runFormulaTests.sh
  scripts/runFunctionTests-27.bat
  scripts/runFunctionTests.bat
  tests/integration_tests/validation/formula/test_formula_conformance_suite.py
  tests/integration_tests/validation/formula/test_formula_function_registry_conformance_suite.py
  tests/integration_tests/validation/validation_util.py
Labels: enhancement

#352 ESEF 2022 validations
  arelle/plugin/validate/ESEF_2022/Const.py
  arelle/plugin/validate/ESEF_2022/DTS.py
  arelle/plugin/validate/ESEF_2022/Dimensions.py
  arelle/plugin/validate/ESEF_2022/Util.py
  arelle/plugin/validate/ESEF_2022/__init__.py
  arelle/plugin/validate/ESEF_2022/config.xml
  arelle/plugin/validate/ESEF_2022/resources/authority-validations.json
  pyproject.toml
Labels: enhancement

#339 Log error and avoid crash on plugin load failure
  arelle/CntlrWinMain.py
  arelle/PluginManager.py
Labels: bug

#369 Handle semver versions in Updater.py
  arelle/Updater.py
  tests/unit_tests/arelle/conftest.py
  tests/unit_tests/arelle/test_updater.py
Labels: enhancement

#371 Type Checking Fixes for ESEF 2022
  arelle/plugin/validate/ESEF_2022/Util.py
  arelle/plugin/validate/ESEF_2022/__init__.py
Labels: bug

#370 Additions to diagnostic output
  .github/ISSUE_TEMPLATE/bug.yml
  arelle/SystemInfo.py
  tests/unit_tests/arelle/test_system_info.py
Labels: enhancement

#368 Issue-365 dynamic version.py
  .github/workflows/build-mac.yml
  .github/workflows/build-windows.yml
  .gitignore
  arelle/Version.py
  buildVersion.py
  distro.py
  scripts/buildLinuxDist.sh
  tests/unit_tests/arelle/test_version.py
Labels: enhancement

#382 Fix runtime.txt syntax.
  runtime.txt
Labels: bug

#383 Optimize schema loading.
  arelle/ModelXbrl.py
Labels: enhancement

#378 Add mypy and pytest caches to gitignore.
  .gitignore
Labels: enhancement
